AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RiskApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../app/
      Handler: app.handler
      Runtime: python3.11
      Architectures: [arm64]
      MemorySize: 1024
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /predict
            Method: post
      Environment:
        Variables:
          S3_BUCKET: !Ref ModelBucket

  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bnpl-credit-risk-model-bucket-anthonyb

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict"